name: Hexo Blog Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Prepare Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Deploy
      run: |
        npm install
        ./node_modules/hexo/bin/hexo clean
        ./node_modules/hexo/bin/hexo generate
        echo "Deploy done!"
